name: MCAutoRestart
version: '${project.version}'
main: com.mcautorestart.MCAutoRestart
api-version: '1.20'
authors: [MCAutoRestartTeam]
description: Advanced plugin for automatic server restart with conditional restart, plugin integration, and flexible configuration
commands:
  autorestart:
    description: Control automatic server restarts
    usage: /<command> [enable|disable|status|set|reload|now|condition|api|sounds|effects|language]
    permission: mcautorestart.admin
permissions:
  mcautorestart.admin:
    description: Allows control of automatic server restarts
    default: op 
